name: sf_env
channels:
- snowflake
dependencies:
- python=3.10.*
- snowflake.core=1.0.2
- trulens-connectors-snowflake=1.2.11
- trulens-core=1.2.9
- trulens-feedback=1.2.11
- trulens-providers-cortex=1.2.11
- streamlit-extras=0.4.0